.github/workflows/notify-slack-on-pr.yml
Add notify-slack-on-pr.yml from main branch
=> Add notify-slack-on-pr.yml from main branch

src/assets/css/main.css
=> Git Action Test

src/views/Authentication/IndividualUserRegisterView.vue
=> [update] #14 - 거주 시 안나오는 오류 수정

src/stores/useJobStore.js
[update] #16 - 옵션리스트 직무 안나오는 에러 수정
=> [update] #16 - 옵션리스트 직무 안나오는 에러 수정

.github/workflows/notify-slack-on-pr.yml
[chore] #14 - git action 설정파일 수정
=> [chore] #14 - git action 설정파일 수정

node_modules/.package-lock.json, package-lock.json, package.json, src/api/services/authenticationService.js, src/views/Authentication/IndividualUserRegisterView.vue
이 PR은 회원가입 시 직업 명 수정 입니다.
- #2 
- [다른 관련 링크]
- 회원가입 시 직업 명 수정
=> 회원가입 시 직업 명 수정

src/api/services/individualUserService.js, src/views/Authentication/IndividualUserRegisterView.vue
이 PR은 첫 네이버 로그인 시 회원가입 구현 완료입니다.
- #2
- 첫 네이버 로그인 시 회원가입 구현 완료
=> 네이버 로그인 시 회원가입 구현 완료

src/components/SearchFilterModal.vue, src/constants/genderTypes.js, src/constants/searchFilterTypes.js, src/router/index.js, src/router/routes.js, src/utils/format.js, src/views/Admin/CorporateJobPostingManagement.vue, src/views/Admin/CorporateUserProfileReadonly.vue, src/views/Admin/CorporateUserSignup.vue, src/views/Admin/CorporateUserWithdrawal.vue, src/views/Admin/CorporateUsersManagement.vue, src/views/Admin/IndividualUserManagement.vue, src/views/Admin/LogDashboardManagement.vue, src/views/Admin/UserLogAnalysis.vue, src/views/Admin/WisdomManagement.vue, src/views/Common/FullScreenMenu.vue, src/views/CorporateUser/JobPostingManagement.vue, src/views/IndividualUser/JobApplicationStatus.vue, src/views/IndividualUser/JobPostingDetail.vue, src/views/IndividualUser/JobPostingsPage.vue, src/views/IndividualUser/WisdomExplore.vue, src/views/IndividualUser/WisdomExploreDetail.vue
이 PR은  admin 화면 추가입니다.
- #21 
-  admin 화면 추가
=> [feat] #21 - admin 화면 추가

public/index.html, src/api/services/authenticationService.js, src/utils/addressFinder.js, src/views/Authentication/CorporateUserRegisterView.vue, src/views/Authentication/IndividualUserRegisterView.vue, src/views/CorporateUser/CorporateUserProfile.vue
이 PR은 기업 회원 가입 시와 정보 수정 시에 사용할 다음 주소 api 설정, 일반 유저 회원가입, 로그인, 기업유저 회원가입, 로그인 완료 입니다.
- #2
- 기업 회원 가입 시와 정보 수정 시에 사용할 다음 주소 api 설정
- 일반 유저 회원가입, 로그인, 기업유저 회원가입, 로그인 완료
=> 기업 회원 가입 시와 정보 수정 시에 사용할 다음 주소 api 설정, 일반 유저 회원가입, 로그인, 기업유저 회원가입, 로그인 완료

src/api/apiService.js
이 PR은 탈퇴한 유저의 로그인으로 인한 서버에서 410 반환시 리다이렉트 처리입니다.
- #2
- 탈퇴한 유저의 로그인으로 인한 서버에서 410 반환시 리다이렉트 처리
- API 호출 기반의 로그인에서는 서버의 리다이렉션 응답을 브라우저가 직접 처리할 수 없음
- AJAX 요청에서 리다이렉션은 브라우저에서 자동으로 따라가지 않음
```java
if (exception instanceof InternalAuthenticationServiceException ||
exception instanceof AuthenticationServiceException) {
// cause의 cause도 체크 (더 깊이 들어가서 체크)
Throwable rootCause = cause;
while (rootCause != null) {
if (rootCause instanceof DeletedUserException) {
System.out.println("CustomAuthenticationFilter에서 DeletedUserException 잡음");
response.setStatus(HttpServletResponse.SC_GONE);
return;
}
rootCause = rootCause.getCause();
}
}
```
410 error 발생 시 인터셉터에서 감지하여 탈퇴회원 안내페이지로 리다이렉트
```jsx
instance.interceptors.response.use(
response => response,
async error => {
const originalRequest = error.config; …
```
=> 탈퇴한 유저의 로그인으로 인한 서버에서 410 반환시 리다이렉트 처리

src/api/services/individualUserService.js, src/utils/format.js, src/views/IndividualUser/WisdomExplore.vue, src/views/IndividualUser/WisdomExploreDetail.vue, src/views/IndividualUser/WisdomShare.vue, src/views/IndividualUser/WisdomShareDelete.vue, src/views/IndividualUser/WisdomShareRegister.vue
이 PR은 지혜 나눔/등록 관련 API 연동 입니다.
- #10 
- 지혜 나눔 전체 목록 조회
- 지헤 나눔 삭제
- 지헤 나눔 등록
- 지혜 탐색 전체 목록 조회
- 지혜 나눔/탐색 상세 조회
=> [feat] #10 - 지혜 나눔/등록 관련 API 연동

src/api/services/authenticationService.js, src/router/index.js, src/router/routes.js, src/views/Common/CorporateDeleteSuccess.vue, src/views/CorporateUser/CorporateUserDelete.vue, src/views/IndividualUser/IndividualUserDelete.vue
이 PR은회원 탈퇴와 회원 탈퇴 확인 화면 및 기능 추가 입니다.
- #2
- 회원 탈퇴와 회원 탈퇴 확인 화면 및 기능 추가
=> 회원 탈퇴와 회원 탈퇴 확인 화면 및 기능 추가

src/views/Admin/CorporateJobPostingManagement.vue, src/views/IndividualUser/JobPostingDetail.vue
이 PR은 서비스 관리자 채용공고 조회 기능입니다.
- #18 
- 채용공고 목록 조회 시, 공고별로 공고 상태 라벨 추가
- 삭제하기 버튼 가운데 정렬 및 최대 가로 길이 설정
- 채용공고 상세 조회 페이지에서 채용 정보 폰트 크기 더 크게 설정
=> [chore] #18 - 공고 상태 라벨 추가

src/views/Admin/IndividualUserManagement.vue
이 PR은 개인회원 목록 css 수정입니다.
- #18 
- 개인 회원 정보 css 변경
=> [chore] #18 - 개인회원 목록 css 변경

src/api/services/corporateUserService.js, src/views/CorporateUser/CorporateUserProfile.vue
이 PR은 기업회원 정보 조회 및 수정입니다.
- #46 
- 기업회원 정보 조회 및 수정 가능
- 정보 조회 화면 css 수정
- .addr-field & .addr-field-detail 클래스 추가
=> [feat] #46 - 기업회원 정보 조회 및 수정

src/api/services/adminServiece.js, src/api/services/individualUserService.js, src/views/Admin/CorporateJobPostingManagement.vue, src/views/IndividualUser/JobPostingDetail.vue
이 PR은 서비스 관리자 채용공고 API입니다.
- #18 
- 채용공고 목록 조회, 채용공고 상세 정보 조회, 채용공고 삭제 API 분리
=> [chore] #18 - 서비스 관리자 채용공고 관련 api 분리

src/api/services/adminServiece.js, src/api/services/individualUserService.js, src/constants/applyTypes.js, src/router/index.js, src/router/routes.js, src/views/Admin/CorporateJobPostingManagement.vue, src/views/Common/FullScreenMenu.vue, src/views/CorporateUser/CorporateUserJobPostingDetail.vue, src/views/CorporateUser/JobPostingManagement.vue, src/views/IndividualUser/JobApplicationStatus.vue, src/views/IndividualUser/JobPostingDetail.vue, src/views/IndividualUser/JobPostingsPage.vue
이 PR은 채용 공고 지원 / 취소 / 지원 목록 API 연동 입니다.
- #45 
- 채용 공고 지원 / 취소 / 지원 목록 API 연동
=> [feat] #45 - 채용 공고 지원 / 취소 / 지원 목록 API 연동

src/App.vue, src/api/services/corporateUserService.js, src/assets/css/main.css, src/components/BottomNavigation.vue, src/components/HeaderComponent.vue, src/views/Common/MainView.vue, src/views/CorporateUser/JobPostingRegister.vue
이 PR은 기업회원 공고등록 API 연동 입니다.
- #41 
- 기업회원 공고등록 API 연동
=> [feat] #41 - 기업회원 공고등록 API 연동

proxy.js, src/views/Admin/UserLogAnalysis.vue
…
이 PR은 kibana 대시보드를 직접 브라우저에서 요청하는 것이 아닌 express에서 요청 후 NAT게이트웨이를 통해서만 요청하여 cloudflare access group 설정을 통해 보안 강화 입니다.
- #84
-  kibana 대시보드를 직접 브라우저에서 요청하는 것이 아닌 express에서 요청 후 NAT게이트웨이를 통해서만 요청하여 cloudflare access group 설정을 통해 보안 강화
=> [feat] #84 -  kibana 대시보드를 직접 브라우저에서 요청하는 것이 아닌 express에서 요청 후 NAT게이트웨이를 통해서만 요청하여 cloudflare access group 설정을 통해 보안 강화

proxy.js, src/views/Admin/UserLogAnalysis.vue
이 PR은 키바나 대시보드 보안을 위한 변경입니다.
- #84
- 키바나 대시보드 보안을 위한 변경
=> [feat] #84 - 키바나 대시보드 보안을 위한 변경
